// export const manufacturers = [
//     "Acura",
//     "Alfa Romeo",
//     "Aston Martin",
//     "Audi",
//     "Bentley",
//     "BMW",
//     "Buick",
//     "Cadillac",
//     "Chevrolet",
//     "Chrysler",
//     "Citroen",
//     "Dodge",
//     "Ferrari",
//     "Fiat",
//     "Ford",
//     "GMC",
//     "Honda",
//     "Hyundai",
//     "Infiniti",
//     "Jaguar",
//     "Jeep",
//     "Kia",
//     "Lamborghini",
//     "Land Rover",
//     "Lexus",
//     "Lincoln",
//     "Maserati",
//     "Mazda",
//     "McLaren",
//     "Mercedes-Benz",
//     "MINI",
//     "Mitsubishi",
//     "Nissan",
//     "Porsche",
//     "Ram",
//     "Rolls-Royce",
//     "Subaru",
//     "Tesla",
//     "Toyota",
//     "Volkswagen",
//     "Volvo",
//   ];

  export const manufacturers = [
    "Abarth",
    "AC",
    "Acura",
    "AIXAM",
    "Alfa Romeo",
    "Alpine",
    "Arash",
    "Ariel",
    "Artega",
    "Ascari",
    "Aston Martin",
    "Audi",
    "AvtoVAZ",
    "BAIC",
    "Bentley",
    "BMW",
    "Borgward",
    "Brilliance",
    "Bristol",
    "Bufori",
    "Bugatti",
    "Buick",
    "Byton",
    "Cadillac",
    "Caterham",
    "Changan",
    "Changhe",
    "Chery",
    "Chevrolet",
    "Chrysler",
    "Citroen",
    "Coda",
    "CT&T",
    "Dacia",
    "Daewoo",
    "DAF",
    "Daihatsu",
    "Datsun",
    "Dodge",
    "Donkervoort",
    "DS",
    "Ferrari",
    "Fiat",
    "Fisker",
    "Force Motors",
    "Ford",
    "Foton",
    "GAZ",
    "Geely",
    "Genesis",
    "Ginetta",
    "GMC",
    "Great Wall",
    "Haima",
    "Hino",
    "Holden",
    "Honda",
    "Hyundai",
    "Iconic",
    "Infiniti",
    "Isuzu",
    "JAC",
    "Jaguar",
    "Jeep",
    "JMC",
    "Kia",
    "Koenigsegg",
    "Lamborghini",
    "Lancia",
    "Land Rover",
    "Landwind",
    "Lexus",
    "Lifan",
    "Lincoln",
    "Lotus",
    "Luxgen",
    "Magna Steyr",
    "Mahindra",
    "Maserati",
    "Maxus",
    "Maybach",
    "Mazda",
    "Mazzanti",
    "McLaren",
    "Mercedes-Benz",
    "MG",
    "Mini",
    "Mitsubishi",
    "Mitsuoka",
    "Morgan",
    "Morris",
    "NIO",
    "Nissan",
    "Noble",
    "Opel",
    "Pagani",
    "Perodua",
    "Peugeot",
    "Polestar",
    "Pontiac",
    "Porsche",
    "Proton",
    "Ram",
    "Reliant",
    "Renault",
    "Rimac",
    "Rivian",
    "Rolls-Royce",
    "RUF",
    "Saab",
    "Saleen",
    "Saturn",
    "Scion",
    "SEAT",
    "Senova",
    "SIN Cars",
    "Skoda",
    "Smart",
    "Spyker",
    "Ssangyong",
    "Subaru",
    "Suzuki",
    "Tata",
    "Tatra",
    "Tesla",
    "Toyota",
    "Trumpchi",
    "TVR",
    "Vauxhall",
    "Volkswagen",
    "Volvo",
    "W Motors",
    "Wiesmann",
    "Zenos",
    "Zenvo",
  ];

  export const yearsOfProduction = [
    { title: "Year", value: "" },
    { title: "2015", value: "2015" },
    { title: "2016", value: "2016" },
    { title: "2017", value: "2017" },
    { title: "2018", value: "2018" },
    { title: "2019", value: "2019" },
    { title: "2020", value: "2020" },
    { title: "2021", value: "2021" },
    { title: "2022", value: "2022" },
    { title: "2023", value: "2023" },
    { title: "2024", value: "2024" },
  ];
  
  export const fuels = [
    {
      title: "Diesel",
      value: "Diesel",
    },
    {
      title: "Gas",
      value: "Gas",
    },
    {
      title: "Electricity",
      value: "Electricity",
    },
  ];
  
  export const footerLinks = [
    {
      title: "About",
      links: [
        { title: "How it works", url: "/" },
        { title: "Featured", url: "/" },
        { title: "Partnership", url: "/" },
        { title: "Bussiness Relation", url: "/" },
      ],
    },
    {
      title: "Company",
      links: [
        { title: "Events", url: "/" },
        { title: "Blog", url: "/" },
        { title: "Podcast", url: "/" },
        { title: "Invite a friend", url: "/" },
      ],
    },
    {
      title: "Socials",
      links: [
        { title: "Discord", url: "/" },
        { title: "Instagram", url: "/" },
        { title: "Twitter", url: "/" },
        { title: "Facebook", url: "/" },
      ],
    },
  ];